### PR TITLE
Replace single monitored log dir with separate server and web

### PR DESCRIPTION
**Pull request by manics**
https://github.com/openmicroscopy/ansible-role-omero-server/tree/2.0.0-m1 and https://github.com/openmicroscopy/ansible-role-omero-web/tree/1.0.0-m3 change the location of OMERO.server and OMERO.web. This PR replaces the single `omero_logmonitor_logs_dir` parameter with `omero_logmonitor_logs_dir_server` and `omero_logmonitor_logs_dir_web`, and changes the defaults to match the default locations for OMERO.server and OMERO.web.

This is a breaking change which mostly affects the default configuration. Advanced configuration will be mostly unaffected.

### CODE REVIEW

**Comment by joshmoore** [comment]
In general, makes sense. Are we currently not getting logs because of this?

**Comment by manics** [comment]
At the moment only the server logs are monitored https://github.com/IDR/deployment/blob/master/ansible/group_vars/omero-hosts.yml#L58

**Comment by manics** [comment]
I've updated travis. There's are several TODOs, but this is no worse than it was before.

**Comment by manics** [comment]
It might be the lack of a valid slack token that's causing a problem, I'll investigate

**Comment by manics** [comment]
@joshmoore I've taken the molecule test out of travis

**Pull request merged**
